[STORAGE]
SQLITE_DB = "db/sample.db"
SCREENSHOTS_DIR = "screenshots"
PDFS_DIR = "pdfs"
PROJECTS_DIR = "projects"
LOGS_DIR = "logs"
REPOS_DIR = "repos"

[API_KEYS]
BING = "<YOUR_BING_API_KEY>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"
OPENAI = "<YOUR_OPENAI_API_KEY>"
GEMINI = "<YOUR_GEMINI_API_KEY>"


[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"

[LOGGING]
LOG_REST_API = "true"
LOG_PROMPTS = "false"